### ISSUE TITLE
Requesting a new build

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#18] opened 2017-11-13 02:12 UTC
:D? cant afford to install all the c# crap

**Comment by stevemk14ebr** [comment] 2017-11-15 15:39
As abnoxious as that was written i do think it might be cool to have to the releases link: https://github.com/KN4CK3R/ReClass.NET/releases scripted to build off the repo. In my mind new commits would trigger a rebuild somewhere and the link would update for everyone, thoughts on how to do this @Timboy67678 or @KN4CK3R  or whoever

**Comment by I-MrFixIt-I** [comment] 2017-11-15 17:06
I don't do much with GitHub, but Jenkins, Docker or maybe even TeamCity might be a solution?
We use SVN and TeamCity in business and it works quite well.

**Comment by Timboy67678** [comment] 2017-11-16 08:24
we could probably use Travis-CI, a lot of open source projects use this as an automatic buildbot

**Comment by LWSS** [comment] 2018-12-20 21:37
Bump, I use this a lot on linux but there's a lot of bugs that I think are patched in the master.

Building it is a bit cumbersome... I did try for *quite* a while, but the linux solution is setup for some remote server, idk what packages are used, and i'm not familiar with .NET.

**Comment by stevemk14ebr** [comment] 2018-12-21 18:38
If we can get a common docker container to build on linux that'd be a walk in the park for new comers. Windows containers are trash though, a bat file might be better there

**Comment by KN4CK3R** [comment] 2019-04-15 20:47
Duplicate of #100.

**Closed by KN4CK3R** 2019-04-15 20:47 UTC
